### ISSUE TITLE
avoid using red/green in the same plot

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/eisaR#10]
E.g. `plotEISA()`, vignette figures (from @federicomarini)

**Comment by federicomarini** [comment]
That was just a thought after I built the vignette and scrolled through that 😉 
Some shade of blue maybe instead of green? I'm a fan of `steelblue` but maybe you have an FMI-corporate-design-blue? 😄

**Comment by mbstadler** [comment]
Good catch, it's aleady done - thanks @csoneson for the quick fix!
