### ISSUE TITLE
I got only one bam file, it looks from C11_R1_val_1.fq.

### ISSUE THREAD

**Issue by bihuaf** [fmicompbio/eisaR#25]
Codes were used to get bam file:
proj2 <- qAlign(sampleFile = "RNAseqanalysis/exonintron2/rna_paired.txt", 
                            genome = RNAseqanalysis/exonintron2/Homo_sapiens.GRCh38.86.dna.primary_assembly.fa",
                             aligner = "Rhisat2", splicedAlignment = TRUE)
rna_paired.txt is below:
FileName1	FileName2	SampleName
C11_R1_val_1.fq	C11_R2_val_2.fq	C11
paired fastq files:  C11_R1_val_1.fq   C11_R2_val_2.fq
I got only one bam file, it looks from C11_R1_val_1.fq.
C11_R1_val_1_114c40627abc.bam.txt
C11_R1_val_1_114c40627abc.bam
C11_R1_val_1_114c40627abc.bam.bai
Is it correct?
Thank you.

**Comment by csoneson** [comment]
Yes, it is normal to only get one bam file when aligning paired-end data. You should see in the command written in the `QuasR` log file that both the forward and reverse reads are taken into account in the alignment, and also in the bam file you should see that the alignments come from paired-end data.

**Comment by bihuaf** [comment]
Thank you very much!
