### ISSUE TITLE
Missing genome size checks?

### ISSUE THREAD

**Issue by saketkc** [fmicompbio/eisaR#26]
Thanks for developing this package.

For the below linkedgenome/gtf, the default value of 90bp extension on the introns results in an error which I think seems to be arising from `intron+flankLength` extending beyond the chromosome boundaries. Does this make sense to you?

[genome_file link](ftp://ftp.ensembl.org/pub/release-101/fasta/mustela_putorius_furo/dna/Mustela_putorius_furo.MusPutFur1.0.dna.toplevel.fa.gz); 
[gtf_file link](ftp://ftp.ensembl.org/pub/release-100/gtf/mustela_putorius_furo/Mustela_putorius_furo.MusPutFur1.0.100.gtf.gz)

```R
gtf_file <- 
genome_file <- ferret_genome_file

grl <- eisaR::getFeatureRanges(
  gtf = gtf_file,
  featureType = c("spliced", "intron"), 
  intronType = "separate", 
  flankLength = 90L, 
  joinOverlappingIntrons = FALSE, 
  verbose = TRUE
)
eisaR::exportToGtf(
  grl,
  filepath = paste0(gtf_file, ".90forsalmon.expanded.gtf")
)

write.table(
    metadata(grl)$corrgene,
    file = paste0(gtf_file, ".90forsalmon.expanded.features.tsv"),
    row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t"
)

df <- eisaR::getTx2Gene(
    grl, filepath = paste0(gtf_file, ".90forsalmon.tx2gene.tsv")
)


genome <- Biostrings::readDNAStringSet( genome_file )
names(genome) <- sapply(strsplit(names(genome), " "), .subset, 1)

seqs <- GenomicFeatures::extractTranscriptSeqs(
  x = genome,
  transcripts = grl
)
````

```bash
Import genomic features from the file as a GRanges object ... 
OK

Prepare the 'metadata' data frame ... 
OK

Make the TxDb object ... 
Warning message in .get_cds_IDX(mcols0$type, mcols0$phase):
"The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored."
OK

'select()' returned 1:1 mapping between keys and columns

Extracting spliced transcript features

Extracting introns using the separate approach

Error in h(simpleError(msg, call)): error in evaluating the argument 'value' in selecting a method for function 'unsplit': some ranges in 'at' are off-limits with respect to their corresponding
  sequence in 'x'
```

**Comment by csoneson** [comment]
This is a correct observation. The problem is that from the gtf only, we don't know the size of the chromosomes (so while we could make sure that there are no negative coordinates, we can't check whether we go beyond the end of the chromosome). If you extract the chromosome lengths from your genome file, you can fix the `GRanges` object manually using the `GenomicRanges::restrict()` function.

**Comment by saketkc** [comment]
Thanks @csoneson. I tried your suggestion, but it still results in an error. Maybe the issue is something else. I will try to hunt it down, but your help is appreciated.

```R
chrom_sizes <- read.csv("chrom_sizes.csv")
chrom_ends <- chrom_sizes$length
names(fchrom_ends) <- chrom_sizes$chrom

grl <- eisaR::getFeatureRanges(
  gtf = gtf_file,
  featureType = c("spliced", "intron"), 
  intronType = "separate", 
  flankLength = 90L, 
  joinOverlappingIntrons = FALSE, 
  verbose = TRUE
)
grl <- restrict(grl, end=chrom_ends)
````

```bash
Import genomic features from the file as a GRanges object ... 
OK

Prepare the 'metadata' data frame ... 
OK

Make the TxDb object ... 
Warning message in .get_cds_IDX(mcols0$type, mcols0$phase):
"The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored."
OK

'select()' returned 1:1 mapping between keys and columns

Extracting spliced transcript features

Extracting introns using the separate approach

Warning message in V_recycle(x, skeleton, x_what = x_what, skeleton_what = skeleton_what):
"'length(x)' is not a multiple of 'NROW(end)'"
Error in h(simpleError(msg, call)): error in evaluating the argument 'value' in selecting a method for function 'unsplit': some ranges in 'at' are off-limits with respect to their corresponding
  sequence in 'x'
```

**Comment by saketkc** [comment]
Thanks @csoneson for the prompt response. My understanding from the [documentation ](https://bioconductor.org/packages/release/bioc/manuals/GenomicRanges/man/GenomicRanges.pdf)of `intra-range-methods` is that `restrict` can be applied to `GRangesList` as well?

In any case, running `restrict` with `endoapply` with the above linked GTF did not finish in a couple of hours so I had to kill it. Appreciate any thoughts you have.

Thanks!
Saket

**Comment by csoneson** [comment]
You could try to add a `Seqinfo` to the `GRangesList` object and use `trim()`: 

```
seqinfo(grl) <- Seqinfo(seqnames = chrom_sizes$chrom, seqlengths = chrom_sizes$length)
trim(grl)
```

**Comment by saketkc** [comment]
Thanks a lot @csoneson! I used a slight modification from your suggestion:
```R
seqinfo(grl)@seqlengths <- chrom_sizes[seqinfo(grl)@seqnames,]$length
grl <- trim(grl)
```
and it seems to work now.
