### ISSUE TITLE
Missing genes in regions from getRegionsFromTxDb

### ISSUE THREAD

**Issue by HelloYiHan** [fmicompbio/eisaR#34]
Hi Sir,

I have a question about eisaR. I don't find some genes in the eisa result, such as IGF1R (Entrez:3480, Ensembl: ENSG00000140443). Then I go back to the code and find this gene is not in the regions obtained from getRegionsFromTxDb function:
```
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
regs<- eisaR::getRegionsFromTxDb(txdb = TxDb.Hsapiens.UCSC.hg38.knownGene, strandedData = TRUE)
3480 %in% names(regs$exons)
False
```
However,  IGF1R is in the original txdb object:
```
select(TxDb.Hsapiens.UCSC.hg38.knownGene, keys=c("3480"), columns=c("TXNAME"), keytype="GENEID")

   GENEID            TXNAME
1    3480 ENST00000649865.1
2    3480 ENST00000650285.1
3    3480 ENST00000559925.5
4    3480 ENST00000558355.1
```

I was wondering why there was not such gene in regs and how to study this gene with eisa.

Thank you so much,
Yi

**Comment by csoneson** [comment]
Hi Yi,

the reason that this gene is not included in the output is that it overlaps another gene in the TxDb: 

```
GRanges object with 2 ranges and 0 metadata columns:
            seqnames            ranges strand
               <Rle>         <IRanges>  <Rle>
  100616432    chr15 98784416-98784512      +
       3480    chr15 98648529-98964540      +
```

The `getRegionsFromTxDb` function takes a conservative approach and filters out such genes (see the documentation of the function), since reads that come from the shared region can not be unambiguously assigned to one or the other gene.

**Comment by HelloYiHan** [comment]
Thank you!

**Comment by HelloYiHan** [comment]
Hi Charlotte,

I hope you remember this issue.

Our team really wants to study the IGF1R gene. Would it be possible that we remove the overlapping genes (such as 100616432) and get  the gene 3480 in the regions obtained from getRegionsFromTxDb. Or do you have any other solutions?

Thank you so much for your kind help!

Yi

**Comment by csoneson** [comment]
Removing the 100616432 gene will allow you to get the regions from `eisaR` for gene `3480`. However, keep in mind that it will not address the underlying ambiguity - any read that maps to the overlapping region could still come from either of the genes. So if you go this way, I would recommend to at least look at your data in a genome browser, specifically in the (relatively short) overlapping region, to convince yourself that this is sensible.
